#:schema node_modules/wrangler/config-schema.json
name = "ducheng"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "463a09b5e097484fb85b6f9ed02d85f2" }
]
